# Generated by Django 3.2.6 on 2021-08-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dblinkall'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('comment', models.CharField(max_length=1000, null=True)),
                ('user', models.CharField(max_length=50, null=True)),
                ('other_user', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
