# Generated by Django 3.2.6 on 2021-12-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211202_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbproject',
            old_name='comment',
            new_name='remark',
        ),
        migrations.RemoveField(
            model_name='dblinkall',
            name='info',
        ),
        migrations.RemoveField(
            model_name='dblinkall',
            name='user',
        ),
        migrations.AddField(
            model_name='dbproject',
            name='global_datas',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dbproject',
            name='user_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dbproject',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dbproject',
            name='other_user',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dbproject',
            name='user',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
